[feat] 경로 이미지 생성하기 - 비동기 처리 (#13)
trip-draw/trip-draw.github.io pull request #14
Opened 2023-08-13 13:47 UTC by greeng00se

비동기 처리에 관한 글을 작성해보았습니다.  

편하게 읽으시려면 [블로그 글](https://greeng00se.github.io/40)을 참고 부탁드립니다!

2023-08-14 09:16 UTC, Jaeyoung22 requested changes
글 잘 읽었습니다 고생했습니다
몇 가지 제안 사항이 있어서 커멘트 남깁니다
확인해주세요!

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +따라서 비동기로 이미지 생성 요청을 처리하여 사용자의 경험을 증가시킬 수 있다고 생각했습니다.
`경험을 증가시킨다`는 말이 제게는 어색하게 들리네요.
`경험을 높이다`라는 말이 자주 쓰이는 것으로 검색이 되네요?

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +소요 시간이 1초 이상 튀는 경우가 존재하기에 이미지 생성을 비동기 처리하고 여행 종료와 감상 생성 기능의 응답 시간을 개선하는 것이 더 중요하다고 생각했습니다.
`튄다`는 표현이 어색한 것 같아요!
`소요 시간이 1초 이상 걸리는 경우`로 바꾸는 건 어떨까요?

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +따라서 추후에 더 짧은 간격으로 위치 정보를 저장하는 경우 대비 이미지 생성은 비동기로 처리하는 것이 합당하다고 생각했습니다.
`저장하는 경우를 대비하여` 로 바꾸는 건 어떨까요?

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +> 7.7. Task Execution and Scheduling, Spring Boot Docs
👍

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +```mermaid
👍 👍

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +인터페이스를 사용한다면 다음과 같은 형태로 될 것 입니다.
`형태일 것 입니다`로 변경하는 건 어떨까요?

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +인터페이스를 사용한다면 다음과 같은 형태로 될 것 입니다.
`형태입니다`가 베스트인 것 같긴 하지만... 문맥상..

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +이는 패키지 간 의존성은 해결되었지만, 이미지 경로 저장을 위해 받는 tripId와 같이 논리적인 의존성은 아직 해결되지 않았습니다.
`이는`은 제거해도 좋을 것 같아요.
넣어야 할 말이 필요하다면 `이 방법으로`나, `이와 같이`는 어떨까요?

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +이는 패키지 간 의존성은 해결되었지만, 이미지 경로 저장을 위해 받는 tripId와 같이 논리적인 의존성은 아직 해결되지 않았습니다.
더해서, 
`이미지 경로 저장을 위해 받는 tripId와 같이 논리적인 의존성은` 이 문장이 비문이라 잘 이해가 되지 않네요.
`이미지 경로 저장을 위해 tripId를 받아야하는 등의 논리적인 의존성은` 등의 문장으로 변경해보는 건 어떨까요?

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +스프링의 애플리케이션 이벤트를 사용하면 비즈니스 로직의 비관심사(ex 경로 이미지 생성)을 효율적인 방법으로 처리할 수 있습니다.
ex 뒤에 . 찍어라... 열받게 하지말고..

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +이벤트를 구독하는 도메인의 행위를 담고 있는 이벤트를 발행(ex RouteImageGenerateEvent)한다면 논리적인 의존 관계가 남아있기에 이벤트를 사용하는 의미가 없어집니다.
. 찍어라... 222

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +이벤트를 구독하는 도메인의 행위를 담고 있는 이벤트를 발행(ex RouteImageGenerateEvent)한다면 논리적인 의존 관계가 남아있기에 이벤트를 사용하는 의미가 없어집니다.
오 그렇군요 처음 알아갑니다 감사합니다

2023-08-14 09:16 UTC, Jaeyoung22 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +처음에는 테스트에서만 동기로 설정 후 검증하려고 했습니다.
이 때도 많이 배웠습니다 ㄱㅅㄱㅅ

2023-08-14 13:28 UTC, greeng00se commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +소요 시간이 1초 이상 튀는 경우가 존재하기에 이미지 생성을 비동기 처리하고 여행 종료와 감상 생성 기능의 응답 시간을 개선하는 것이 더 중요하다고 생각했습니다.
좋은 것 같습니당 👍

2023-08-14 13:30 UTC, greeng00se commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +인터페이스를 사용한다면 다음과 같은 형태로 될 것 입니다.
`다음과 같은 구조로 변경됩니다.`  은 어떤가요?

2023-08-14 13:31 UTC, greeng00se commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +스프링의 애플리케이션 이벤트를 사용하면 비즈니스 로직의 비관심사(ex 경로 이미지 생성)을 효율적인 방법으로 처리할 수 있습니다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 사실 ) 붙이고 싶었는데 괄호 안이라..

2023-08-14 13:38 UTC, greeng00se commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +이벤트를 구독하는 도메인의 행위를 담고 있는 이벤트를 발행(ex RouteImageGenerateEvent)한다면 논리적인 의존 관계가 남아있기에 이벤트를 사용하는 의미가 없어집니다.
이 부분 너무 완고한 느낌이라서 

> 이벤트를 구독하는 도메인의 행위를 담고 있는 이벤트를 발행(ex. RouteImageGenerateEvent)한다면 논리적인 의존 관계가 남아있기에 이벤트를 적절히 사용했다고 보기 어렵습니다.
  
로 변경하겠습니다

2023-08-16 01:16 UTC, beer-2000 approved these changes
최고최고

2023-08-17 08:39 UTC, Jaeyoung22 approved these changes
다니습셨하생고

2023-08-17 08:43 UTC, Combi153 approved these changes
진짜 고생 많으셨습니다!

2023-08-17 08:43 UTC, Combi153 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +현재 여행을 마치는 경우, 감상을 생성하는 경우 이미지 생성 요청이 이루어집니다.
`현재 코드에서는 여행을 마치거나 감상을 생성하는 경우`는 어떤가요?

2023-08-17 08:43 UTC, Combi153 commented on blog/2023-08-13-경로 이미지 생성하기 - 비동기 처리/2023-08-13-경로 이미지 생성하기 - 비동기 처리.md
> +경로 이미지 생성의 경우 위치 정보의 개수에 정비례하여 생성 시간이 증가합니다.
`이때 여행에 포함된 위치정보의 개수에 정비례하여 경로 이미지 생성 시간이 증가합니다.` 는 어떤가요?

2023-08-17 08:47 UTC, merged