[feat] 경로 이미지 그리기 기술 선택 글 작성
trip-draw/trip-draw.github.io pull request #7
Opened 2023-07-27 00:00 UTC by greeng00se

경로 이미지 그리기 기술 선택에 대한 글을 작성했습니다.

추가했으면 하는 부분이나 수정하면 좋을 것 같은 부분 남겨주시면 확인하고 반영하겠습니답 😄

2023-07-27 00:13 UTC, beer-2000 approved these changes
너무 좋은데요? 👍

2023-07-27 00:14 UTC, otter66 approved these changes
기술 선택 이유들을 간결하게 잘 정리해주셔서 이해에 어려움이 없었습니다!!! 👍
마지막에 팀원들을과의 공유 방법까지 알려주셔서 더욱 좋았습니다!!!

2023-07-27 00:55 UTC, pingu244 approved these changes
완벽✨

2023-07-27 03:32 UTC, 2chang5 commented
쌍따봉 드리겠습니다.

2023-07-27 06:36 UTC, Jaeyoung22 requested changes
글의 내용이 논리정연하고 명확하네요! 커멘트 하나만 확인해주세요~

2023-07-27 06:36 UTC, Jaeyoung22 commented on blog/2023-07-27-경로 이미지 생성하기 - 기술 선택/2023-07-27-경로 이미지 생성하기 - 기술 선택.mdx
> +저희는 현재 클라이언트의 바쁜 일정과 기능 구현에 있어 약간의 연산이 들어간다는 부분에서 백엔드에서 이미지를 생성하기로 결정을 내렸습니다.
저희는 현재 클라이언트의 바쁜 일정과, 기능 구현에 약간의 연산이 들어간다는 부분을 고려하여~~ 로 수정하는 건 어떨까요?

2023-07-28 00:55 UTC, Combi153 approved these changes
너무 좋습니다 이해가 잘 돼요~

2023-07-28 01:29 UTC, greeng00se commented on blog/2023-07-27-경로 이미지 생성하기 - 기술 선택/2023-07-27-경로 이미지 생성하기 - 기술 선택.mdx
> +저희는 현재 클라이언트의 바쁜 일정과 기능 구현에 있어 약간의 연산이 들어간다는 부분에서 백엔드에서 이미지를 생성하기로 결정을 내렸습니다.
좋은데요? 역시 십자말풀이 고수 답네요

2023-07-28 01:36 UTC, 2chang5 approved these changes

2023-07-28 05:15 UTC, Jaeyoung22 approved these changes
고생하셨습니다~~

2023-07-28 05:16 UTC, merged